######################################################################
##
## Filename: uart_drive_test.udo
## Created on: Thu Jul 09 15:06:20 中国标准时间 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
